[ WARN ] Taking screenshot failed: OSError: screen grab failed
Make sure tests are run with a physical or virtual display.
[ WARN ] Taking screenshot failed: OSError: screen grab failed
Make sure tests are run with a physical or virtual display.
[ WARN ] Failed to fetch value for field: Sym.Dev.target_directory
[ WARN ] Traceback (most recent call last):
  File "C:\RobotFramework\sap_testing\Execution\Access_Data.py", line 59, in get_data
    field_value = eval(command)
                  ^^^^^^^^^^^^^
  File "<string>", line 1, in <module>
AttributeError: module 'Data.Symphony.Dev' has no attribute 'target_directory'

[ WARN ] Failed to fetch value for field: Sym.Dev.target_directory
[ WARN ] Traceback (most recent call last):
  File "C:\RobotFramework\sap_testing\Tests\Resource\Merger.py", line 11, in copy_images
    os.makedirs(target_dir)
  File "<frozen os>", line 225, in makedirs
FileNotFoundError: [WinError 3] The system cannot find the path specified: ''

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\RobotFramework\sap_testing\Execution\Access_Data.py", line 59, in get_data
    field_value = eval(command)
                  ^^^^^^^^^^^^^
  File "<string>", line 1, in <module>
AttributeError: module 'Data.Symphony.Dev' has no attribute 'target_directory'

